import type { NextConfig } from "next";

// 26 high-value area pages kept; 146 removed area pages 301-redirect to /bangalore-locations
const nextConfig: NextConfig = {
  images: {
    remotePatterns: [
      {
        protocol: 'https',
        hostname: 'via.placeholder.com',
      },
      {
        protocol: 'https',
        hostname: 'images.unsplash.com',
      },
    ],
  },
  async headers() {
    return [
      {
        source: '/(.*)',
        headers: [
          {
            key: 'X-DNS-Prefetch-Control',
            value: 'on'
          },
          {
            key: 'X-Frame-Options',
            value: 'SAMEORIGIN'
          },
          {
            key: 'X-Content-Type-Options',
            value: 'nosniff'
          },
          {
            key: 'X-XSS-Protection',
            value: '1; mode=block'
          },
          {
            key: 'Referrer-Policy',
            value: 'origin-when-cross-origin'
          },
          {
            key: 'Permissions-Policy',
            value: 'camera=(), microphone=(), geolocation=()'
          }
        ],
      },
    ]
  },
  async redirects() {
    return [
      // 146 removed area pages → /bangalore-locations (301 permanent)
      { source: '/areas/rajajinagar', destination: '/bangalore-locations', permanent: true },
      { source: '/areas/banashankari', destination: '/bangalore-locations', permanent: true },
      { source: '/areas/electronic-city-phase-1', destination: '/bangalore-locations', permanent: true },
      { source: '/areas/electronic-city-phase-2', destination: '/bangalore-locations', permanent: true },
      { source: '/areas/basavanagudi', destination: '/bangalore-locations', permanent: true },
      { source: '/areas/uttarahalli', destination: '/bangalore-locations', permanent: true },
      { source: '/areas/bommanahalli', destination: '/bangalore-locations', permanent: true },
      { source: '/areas/varthur', destination: '/bangalore-locations', permanent: true },
      { source: '/areas/varthur-road', destination: '/bangalore-locations', permanent: true },
      { source: '/areas/marathahalli-bridge', destination: '/bangalore-locations', permanent: true },
      { source: '/areas/kadubeesanahalli', destination: '/bangalore-locations', permanent: true },
      { source: '/areas/panathur', destination: '/bangalore-locations', permanent: true },
      { source: '/areas/belathur', destination: '/bangalore-locations', permanent: true },
      { source: '/areas/carmelaram', destination: '/bangalore-locations', permanent: true },
      { source: '/areas/kadugodi', destination: '/bangalore-locations', permanent: true },
      { source: '/areas/hagadur', destination: '/bangalore-locations', permanent: true },
      { source: '/areas/munnekollal', destination: '/bangalore-locations', permanent: true },
      { source: '/areas/kundalahalli', destination: '/bangalore-locations', permanent: true },
      { source: '/areas/hoodi', destination: '/bangalore-locations', permanent: true },
      { source: '/areas/hope-farm', destination: '/bangalore-locations', permanent: true },
      { source: '/areas/nallurhalli', destination: '/bangalore-locations', permanent: true },
      { source: '/areas/immadihalli', destination: '/bangalore-locations', permanent: true },
      { source: '/areas/siddapura', destination: '/bangalore-locations', permanent: true },
      { source: '/areas/nellurahalli', destination: '/bangalore-locations', permanent: true },
      { source: '/areas/channasandra', destination: '/bangalore-locations', permanent: true },
      { source: '/areas/thubarahalli', destination: '/bangalore-locations', permanent: true },
      { source: '/areas/vinayakanagar', destination: '/bangalore-locations', permanent: true },
      { source: '/areas/brigade-road', destination: '/bangalore-locations', permanent: true },
      { source: '/areas/shivajinagar', destination: '/bangalore-locations', permanent: true },
      { source: '/areas/ulsoor', destination: '/bangalore-locations', permanent: true },
      { source: '/areas/domlur', destination: '/bangalore-locations', permanent: true },
      { source: '/areas/cox-town', destination: '/bangalore-locations', permanent: true },
      { source: '/areas/benson-town', destination: '/bangalore-locations', permanent: true },
      { source: '/areas/frazer-town', destination: '/bangalore-locations', permanent: true },
      { source: '/areas/cooke-town', destination: '/bangalore-locations', permanent: true },
      { source: '/areas/richmond-town', destination: '/bangalore-locations', permanent: true },
      { source: '/areas/langford-town', destination: '/bangalore-locations', permanent: true },
      { source: '/areas/wilson-garden', destination: '/bangalore-locations', permanent: true },
      { source: '/areas/shanti-nagar', destination: '/bangalore-locations', permanent: true },
      { source: '/areas/adugodi', destination: '/bangalore-locations', permanent: true },
      { source: '/areas/madivala', destination: '/bangalore-locations', permanent: true },
      { source: '/areas/koramangala-1st-block', destination: '/bangalore-locations', permanent: true },
      { source: '/areas/koramangala-2nd-block', destination: '/bangalore-locations', permanent: true },
      { source: '/areas/koramangala-3rd-block', destination: '/bangalore-locations', permanent: true },
      { source: '/areas/koramangala-4th-block', destination: '/bangalore-locations', permanent: true },
      { source: '/areas/koramangala-5th-block', destination: '/bangalore-locations', permanent: true },
      { source: '/areas/koramangala-6th-block', destination: '/bangalore-locations', permanent: true },
      { source: '/areas/koramangala-7th-block', destination: '/bangalore-locations', permanent: true },
      { source: '/areas/koramangala-8th-block', destination: '/bangalore-locations', permanent: true },
      { source: '/areas/koramangala-9th-block', destination: '/bangalore-locations', permanent: true },
      { source: '/areas/hennur', destination: '/bangalore-locations', permanent: true },
      { source: '/areas/hbr-layout', destination: '/bangalore-locations', permanent: true },
      { source: '/areas/hbr-layout-1st-block', destination: '/bangalore-locations', permanent: true },
      { source: '/areas/hbr-layout-2nd-block', destination: '/bangalore-locations', permanent: true },
      { source: '/areas/hbr-layout-3rd-block', destination: '/bangalore-locations', permanent: true },
      { source: '/areas/hbr-layout-4th-block', destination: '/bangalore-locations', permanent: true },
      { source: '/areas/hbr-layout-5th-block', destination: '/bangalore-locations', permanent: true },
      { source: '/areas/hrbr-layout', destination: '/bangalore-locations', permanent: true },
      { source: '/areas/kalyan-nagar', destination: '/bangalore-locations', permanent: true },
      { source: '/areas/kalyan-nagar-4th-block', destination: '/bangalore-locations', permanent: true },
      { source: '/areas/horamavu', destination: '/bangalore-locations', permanent: true },
      { source: '/areas/horamavu-banjara-layout', destination: '/bangalore-locations', permanent: true },
      { source: '/areas/ramamurthy-nagar', destination: '/bangalore-locations', permanent: true },
      { source: '/areas/kammanahalli', destination: '/bangalore-locations', permanent: true },
      { source: '/areas/sahakar-nagar', destination: '/bangalore-locations', permanent: true },
      { source: '/areas/sahakara-nagar', destination: '/bangalore-locations', permanent: true },
      { source: '/areas/sanjay-nagar', destination: '/bangalore-locations', permanent: true },
      { source: '/areas/yeshwanthpur', destination: '/bangalore-locations', permanent: true },
      { source: '/areas/yeshwanthpur-industrial-area', destination: '/bangalore-locations', permanent: true },
      { source: '/areas/peenya', destination: '/bangalore-locations', permanent: true },
      { source: '/areas/kengeri', destination: '/bangalore-locations', permanent: true },
      { source: '/areas/jalahalli', destination: '/bangalore-locations', permanent: true },
      { source: '/areas/jalahalli-west', destination: '/bangalore-locations', permanent: true },
      { source: '/areas/rajarajeshwari-nagar', destination: '/bangalore-locations', permanent: true },
      { source: '/areas/jp-nagar-1st-phase', destination: '/bangalore-locations', permanent: true },
      { source: '/areas/jp-nagar-2nd-phase', destination: '/bangalore-locations', permanent: true },
      { source: '/areas/jp-nagar-3rd-phase', destination: '/bangalore-locations', permanent: true },
      { source: '/areas/jp-nagar-4th-phase', destination: '/bangalore-locations', permanent: true },
      { source: '/areas/jp-nagar-5th-phase', destination: '/bangalore-locations', permanent: true },
      { source: '/areas/jp-nagar-6th-phase', destination: '/bangalore-locations', permanent: true },
      { source: '/areas/jp-nagar-7th-phase', destination: '/bangalore-locations', permanent: true },
      { source: '/areas/jp-nagar-8th-phase', destination: '/bangalore-locations', permanent: true },
      { source: '/areas/jp-nagar-9th-phase', destination: '/bangalore-locations', permanent: true },
      { source: '/areas/silk-board', destination: '/bangalore-locations', permanent: true },
      { source: '/areas/jeevan-bima-nagar', destination: '/bangalore-locations', permanent: true },
      { source: '/areas/jayamahal', destination: '/bangalore-locations', permanent: true },
      { source: '/areas/sadashivanagar', destination: '/bangalore-locations', permanent: true },
      { source: '/areas/malleshpalya', destination: '/bangalore-locations', permanent: true },
      { source: '/areas/doddanekundi', destination: '/bangalore-locations', permanent: true },
      { source: '/areas/ramagondanahalli', destination: '/bangalore-locations', permanent: true },
      { source: '/areas/gunjur', destination: '/bangalore-locations', permanent: true },
      { source: '/areas/amruthalli', destination: '/bangalore-locations', permanent: true },
      { source: '/areas/byatarayanapura', destination: '/bangalore-locations', permanent: true },
      { source: '/areas/rmv-extension', destination: '/bangalore-locations', permanent: true },
      { source: '/areas/ganganagar', destination: '/bangalore-locations', permanent: true },
      { source: '/areas/sultanpalya', destination: '/bangalore-locations', permanent: true },
      { source: '/areas/jakkur', destination: '/bangalore-locations', permanent: true },
      { source: '/areas/jakkuru-layout', destination: '/bangalore-locations', permanent: true },
      { source: '/areas/sanjeevini-nagar', destination: '/bangalore-locations', permanent: true },
      { source: '/areas/nandini-layout', destination: '/bangalore-locations', permanent: true },
      { source: '/areas/kacharakana-halli', destination: '/bangalore-locations', permanent: true },
      { source: '/areas/ms-palya', destination: '/bangalore-locations', permanent: true },
      { source: '/areas/jayanti-nagar', destination: '/bangalore-locations', permanent: true },
      { source: '/areas/nri-layout', destination: '/bangalore-locations', permanent: true },
      { source: '/areas/chokkanahalli', destination: '/bangalore-locations', permanent: true },
      { source: '/areas/chikkagubbi', destination: '/bangalore-locations', permanent: true },
      { source: '/areas/thanisandra-main-road', destination: '/bangalore-locations', permanent: true },
      { source: '/areas/hormavu-agara', destination: '/bangalore-locations', permanent: true },
      { source: '/areas/medahalli', destination: '/bangalore-locations', permanent: true },
      { source: '/areas/byrathi-village', destination: '/bangalore-locations', permanent: true },
      { source: '/areas/narayanapura', destination: '/bangalore-locations', permanent: true },
      { source: '/areas/kempapura', destination: '/bangalore-locations', permanent: true },
      { source: '/areas/hebbal-kempapura', destination: '/bangalore-locations', permanent: true },
      { source: '/areas/goraguntepalya', destination: '/bangalore-locations', permanent: true },
      { source: '/areas/doddabommasandra', destination: '/bangalore-locations', permanent: true },
      { source: '/areas/pattandur-agrahara', destination: '/bangalore-locations', permanent: true },
      { source: '/areas/ecc-road', destination: '/bangalore-locations', permanent: true },
      { source: '/areas/sp-road', destination: '/bangalore-locations', permanent: true },
      { source: '/areas/murphy-town', destination: '/bangalore-locations', permanent: true },
      { source: '/areas/seshadripuram', destination: '/bangalore-locations', permanent: true },
      { source: '/areas/vasanth-nagar', destination: '/bangalore-locations', permanent: true },
      { source: '/areas/sarjapur', destination: '/bangalore-locations', permanent: true },
      { source: '/areas/harlur', destination: '/bangalore-locations', permanent: true },
      { source: '/areas/giri-nagar', destination: '/bangalore-locations', permanent: true },
      { source: '/areas/kumaraswamy-layout', destination: '/bangalore-locations', permanent: true },
      { source: '/areas/padmanabhanagar', destination: '/bangalore-locations', permanent: true },
      { source: '/areas/arekere', destination: '/bangalore-locations', permanent: true },
      { source: '/areas/gottigere', destination: '/bangalore-locations', permanent: true },
      { source: '/areas/hulimavu', destination: '/bangalore-locations', permanent: true },
      { source: '/areas/bommasandra', destination: '/bangalore-locations', permanent: true },
      { source: '/areas/mahadevapura', destination: '/bangalore-locations', permanent: true },
      { source: '/areas/itpl', destination: '/bangalore-locations', permanent: true },
      { source: '/areas/banaswadi', destination: '/bangalore-locations', permanent: true },
      { source: '/areas/kr-puram', destination: '/bangalore-locations', permanent: true },
      { source: '/areas/rt-nagar', destination: '/bangalore-locations', permanent: true },
      { source: '/areas/lingarajapuram', destination: '/bangalore-locations', permanent: true },
      { source: '/areas/vidyaranyapura', destination: '/bangalore-locations', permanent: true },
      { source: '/areas/vijay-nagar', destination: '/bangalore-locations', permanent: true },
      { source: '/areas/mathikere', destination: '/bangalore-locations', permanent: true },
      { source: '/areas/kamakshipalya', destination: '/bangalore-locations', permanent: true },
      { source: '/areas/mahalakshmi-layout', destination: '/bangalore-locations', permanent: true },
      { source: '/areas/nagarbhavi', destination: '/bangalore-locations', permanent: true },
      { source: '/areas/attibele', destination: '/bangalore-locations', permanent: true },
      { source: '/areas/jigani', destination: '/bangalore-locations', permanent: true },
      { source: '/areas/chandapura', destination: '/bangalore-locations', permanent: true },
      { source: '/areas/nelamangala', destination: '/bangalore-locations', permanent: true },
    ]
  },
};

export default nextConfig;
